### ISSUE TITLE
docker compose volumes 错误

### ISSUE THREAD

**Issue by liuxy0551** [donknap/dpanel-docs#2]
https://github.com/donknap/dpanel-docs/blob/master/docs/zh-cn/install/compose.md

普通版的 volumes 第二行挂载 panel 文件夹缺失了 `/` 或 './'，会报错，lite 版正常。

<img width="654" alt="image" src="https://github.com/user-attachments/assets/73fa704d-201b-4824-aa77-386a8eaf069a">

**Comment by donknap** [comment]
已修复文档，提供两种挂载目录的说明。
