### ISSUE TITLE
English translation 

### ISSUE THREAD

**Issue by Mongoose69** [donknap/dpanel-docs#3]
I did a quick translation of the readme in case you are interested 

dpanel
DPanel is a Docker visual management panel that provides complete container management functions.

Function introduction
The all-Chinese interface is more suitable for use in a Chinese environment.
Easy to install, takes up very little resources, and is suitable for various NAS devices, boxes, and small servers.
Running in a container mode, no privileged mode is required, no dependence on or intrusion on the host machine, safe and reliable.
Provides complete container creation and management functions, and provides container domain name binding functions to adapt to simple usage scenarios.
The file management function provided can easily and quickly view and debug various files in the container.
Provides complete network management functions to facilitate interconnection and intercommunication between containers, as well as various network configuration requirements.
Supports multiple compose.yml addition methods such as text, remote address, and mount directory to quickly deploy and manage Compose tasks.
Provides basic images and templates in multiple languages, which can quickly build your own images, and can quickly achieve sustainable construction through Zip or Git.
 Video tutorial
https://space.bilibili.com/346309066

Overview

Container management

File management

Image management

Create image

Create Compose

Deploy Compose

System management

**Comment by donknap** [comment]
thk， I will write English documents later
